force-app/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <description>Order header. Contains general information about the purchase, totals, and is linked to the Account.</description>
    <label>Purchase</label>
    <nameField>
        <displayFormat>PUR-{0000}</displayFormat>
        <label>Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase__c/fields/GrandTotal__c.field-meta.xml
<CustomField>
    <fullName>GrandTotal__c</fullName>
    <description>Purchase completion total. Calculated automatically in Apex Trigger (PurchaseLineTrigger) as the lengths of all PurchaseLine__c record categories (Amount * UnitCost).</description>
    <inlineHelpText>Total purchase amount calculated automatically based on purchase lines.</inlineHelpText>
    <label>GrandTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/TotalItems__c.field-meta.xml
<CustomField>
    <fullName>TotalItems__c</fullName>
    <description>The total number of items n this order. This field is calculated automatically using the Apex Trigger on the PurchaseLine__c object. It cannot be edited manually.</description>
    <label>TotalItems</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/PurchaseLine__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Items to Purchases. Stores quantity and price at the time of transaction.</description>
    <label>PurchaseLine</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>PurchaseLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PurchaseLine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseLine__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The quantity of the item purchased in this transaction line.</description>
    <inlineHelpText>Enter the quantity of the item for this line.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/fields/PurchaseId__c.field-meta.xml
<CustomField>
    <fullName>PurchaseId__c</fullName>
    <description>Master-Detail relationship to the parent Purchase record. Ensures cascade deletion of lines if the purchase is removed.</description>
    <inlineHelpText>Select the parent purchase for this line item.</inlineHelpText>
    <label>Purchase</label>
    <referenceTo>Purchase__c</referenceTo>
    <relationshipLabel>PurchaseLine</relationshipLabel>
    <relationshipName>PurchaseLines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <description>The price per unit of the item at the moment of purchase. Used to maintain financial history even if the Item price changes later.</description>
    <inlineHelpText>Enter the price for a single unit of this item.</inlineHelpText>
    <label>UnitCost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PurchaseLineTriggerHandler.cls
public with sharing class PurchaseLineTriggerHandler {

    public static void calculateTotals(List<PurchaseLine__c> lines) {
        Set<Id> purchaseIds = new Set<Id>();
        for (PurchaseLine__c line : lines) {
            if(line.PurchaseId__c != null) {
                purchaseIds.add(line.PurchaseId__c);
            }
        }

        if(purchaseIds.isEmpty()) {
            return;
        }

        // map for updates and speed
        Map<Id, Purchase__c> purchasesToUpdateMap = new Map<Id, Purchase__c>();
        for(Id pId: purchaseIds) {
            purchasesToUpdateMap.put(pId, new Purchase__c(
                    Id = pId,
                    TotalItems__c = 0,
                    GrandTotal__c = 0
            ));
        }

        // get Amount__c, PurchaseId__c, UnitCost__c, for update a Cost
        List<PurchaseLine__c> allLines = [
                SELECT Amount__c, PurchaseId__c, UnitCost__c
                FROM PurchaseLine__c
                WHERE PurchaseId__c IN :purchaseIds
        ];

        // do math section
        for(PurchaseLine__c line: allLines) {
            Purchase__c parent = purchasesToUpdateMap.get(line.PurchaseId__c);
            if(line.Amount__c != null && line.UnitCost__c != null) {
                parent.TotalItems__c += line.Amount__c;
                parent.GrandTotal__c += (line.Amount__c * line.UnitCost__c);
            }
        }

        // small
        if (!purchasesToUpdateMap.isEmpty()) {
            update purchasesToUpdateMap.values();
        }
    }
}